app/webapp/main/forms.py
from flask.ext.wtf import Form
from flask.ext.wtf.file import file_allowed
from flask.ext.pagedown.fields import PageDownField
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, IntegerField, DateField, FloatField
from flask.ext.wtf.file import FileField
from wtforms.validators import Required, Optional, Length, Regexp, InputRequired
from wtforms import ValidationError
from ..usermodels import User
from .. import photos


class EditProfileFormBasic(Form):
    name = StringField('Real name', validators=[Length(0, 64)])
    organisation = StringField('Organisation or company')
    invoice_details = TextAreaField('Invoice details (name + address + VAT number)')
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')


class EditProfileForm(EditProfileFormBasic):
    submit = SubmitField('Update information')


class EditProfileAdminForm(EditProfileFormBasic):
    username = StringField('Username (only letters, numbers, dots or underscores, should start with a letter or number)',
                           validators=[Required(),
                                       Length(1, 64),
                                       Regexp('^[A-Za-z0-9][A-Za-z0-9_.]*$', 0,
                                              'Usernames must have only letters, numbers, dots or underscores and should start with a letter or number')])
    confirmed = BooleanField('Confirmed')
    moderator = BooleanField('Moderator (not applicable for the admin)')
    keycard = StringField('Keycard code')

    photo = FileField('Photo', validators=[Optional(), file_allowed(photos, "Images only!")])

    submit = SubmitField('Update information')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and \
                User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if field.data != self.user.username and \
                User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

class DeleteConfirmationForm(Form):
    delete = BooleanField('Are you sure?')
    deletebutton = SubmitField('Delete')


class SearchUserForm(Form):
    name = StringField('Name', validators=[Optional()])
    id = IntegerField('Id', validators=[Optional()])
    searchbutton = SubmitField('Search')

class EditSkillForm(Form):
    name = StringField('Name', validators=[Required()])
    description = TextAreaField('Description', validators=[Required()])
    submit = SubmitField('Update skill')

class EditResourceForm(Form):
    name = StringField('Name', validators=[Required()])
    description = PageDownField('Description', validators=[Required()])
    active = BooleanField('Active', validators=[Optional()])
    skill_required = BooleanField('Skill required', validators=[Optional()])
    photo = FileField('Photo', validators=[Optional(), file_allowed(photos, "Images only!")])
    price_p_per = IntegerField('Price per period (euro)', validators=[InputRequired()])
    reserv_per = IntegerField('Reservation period (minutes)', validators=[Required()])
    submit = SubmitField('Update resource')

class RequestInvoiceForm(Form):
    invoice_details = TextAreaField('Invoice details (name + address + VAT number)')
    vat_exempt = BooleanField('Are you VAT exempted (vrijstelling van BTW)?', default=False)
    submit = SubmitField('Request invoice')

class ChangeSettingsForm(Form):
    invoice_details = TextAreaField('Invoice details (name + address)')
    vat_number = StringField('VAT number')
    invoice_email = StringField('Invoice e-mail')
    submit = SubmitField('Change settings')

class ExpenseNoteForm(Form):
    total = FloatField('Total cost', validators=[Required()])
    description = StringField('Description', validators=[Required()])
    bank_account = StringField('Bank account', validators=[Required()])
    date = DateField('Date (costs made on)', validators=[Required()], format='%d/%m/%Y')
    file = FileField('File', validators=[Required()])
    submit = SubmitField('Create expense note')

class PayExpenseNoteForm(Form):
    paid = BooleanField('Paid', validators=[Optional()])
    submit = SubmitField('Save')

class ExportPayementsForm(Form):
    start = DateField('Start date', validators=[Required()], format='%d/%m/%Y')
    end = DateField('End date', validators=[Required()], format='%d/%m/%Y')
    only_paid = BooleanField('Only paid', validators=[Optional()])
    submit = SubmitField('Export')

app/webapp/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.qrcode import QRcode
from flask.ext.pagedown import PageDown
from flask.ext.uploads import configure_uploads, UploadSet, IMAGES, EXECUTABLES, AllExcept
from flask.ext.thumbnails import Thumbnail
from config import config
import Mollie
import os


bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
qrcode = QRcode()
pagedown = PageDown()
photos = UploadSet('photos', IMAGES)
expensenotes = UploadSet('expensenotes', AllExcept(EXECUTABLES))
thumb = Thumbnail()
mollie = Mollie.API.Client()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name, url_prefix):

    if url_prefix == "" or url_prefix == "/":
        main_prefix=None
        auth_prefix='/auth'
        static_prefix='/static'
        media_url='_uploads/photos/'
    else:
        if url_prefix.endswith('/'):
            url_prefix=url_prefix[:-1]
        main_prefix=url_prefix
        auth_prefix=url_prefix+'/auth'
        static_prefix='%s/static' % url_prefix
        media_url='%s/_uploads/photos/' % url_prefix[1:]

        from flask_uploads import uploads_mod
        uploads_mod.url_prefix = '%s/_uploads' % url_prefix

    if os.getenv('DEBUG'):
        app = Flask(__name__,
                    static_url_path=static_prefix,
                    static_folder='/opt/project/app/static')
    else:
        app = Flask(__name__,
                    static_url_path=static_prefix,
                    static_folder='/app/static')

    #app = Flask(__name__, static_url_path=static_prefix)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    print('static_folder: %s' % app.static_folder)
    print('static_url_path: %s' % app.static_url_path)
    app.logger.error('static_folder: %s' % app.static_folder)
    app.logger.error('static_url_path: %s' % app.static_url_path)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    qrcode.init_app(app)
    pagedown.init_app(app)
    configure_uploads(app, (photos, expensenotes))

    app.config['MEDIA_FOLDER'] = app.config['UPLOADED_PHOTOS_DEST']
    app.config['MEDIA_URL'] = media_url

    thumb.init_app(app)
    mollie.setApiKey(app.config['MOLLIE_KEY'])

    if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
        from flask.ext.sslify import SSLify
        sslify = SSLify(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix=main_prefix)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix=auth_prefix)

    from decorators import authorise_download
    app.view_functions['_uploads.uploaded_file'] = authorise_download(app.view_functions['_uploads.uploaded_file'])

    return app


app = create_app(os.getenv('FLASK_CONFIG') or 'default', os.getenv('APP_URL_PREFIX'))

app/webapp/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, userviews, resourceviews, skillviews, reservationviews, availableviews, paymentviews, settingsviews
from ..usermodels import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/webapp/main/views.py
from flask import abort, request, current_app, render_template, g
from flask.ext.sqlalchemy import get_debug_queries
from . import main
from ..resourcemodels import Resource

@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n'
                % (query.statement, query.parameters, query.duration,
                   query.context))
    return response


@main.before_app_request
def before_request():
    g.resources = Resource.query.filter_by(active=True).all()


@main.route('/shutdown')
def server_shutdown():
    if not current_app.testing:
        abort(404)
    shutdown = request.environ.get('werkzeug.server.shutdown')
    if not shutdown:
        abort(500)
    shutdown()
    return 'Shutting down...'


@main.route('/', methods=['GET', 'POST'])
def index():
    print('static_folder: %s' % current_app.static_folder)
    print('static_url_path: %s' % current_app.static_url_path)
    current_app.logger.error('static_folder: %s' % current_app.static_folder)
    current_app.logger.error('static_url_path: %s' % current_app.static_url_path)

    return render_template('index.html')


@main.route('/calendar', methods=['GET', 'POST'])
def calendar():
    return render_template('calendar.html')

app/webapp/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination pagination-sm">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/webapp/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{{ config['APP_NAME'] }}{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="header">
    <img src="https://www.budalab.be/wp-content/uploads/2018/06/budalab-logoverkleind2-1.jpg">
</div>

<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://www.budalab.be">BUDA::LAB</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a class="navbar-brand" href="{{ url_for('main.index') }}">CALENDAR</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        RESERVATIONS <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        {% if current_user.can(Permission.MANAGE_RESERVATIONS) %}
                            <li><a href="{{ url_for('main.reservation_overview') }}">Overview</a></li>
                        {% endif %}
                        {% for resource in g.resources %}
                            <li><a href="{{ url_for('main.make_reservation', id=resource.id) }}">{{ resource.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        RESOURCES <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        {% for resource in g.resources %}
                            <li><a href="{{ url_for('main.resource', name=resource.name) }}">{{ resource.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

                {%  if current_user.is_authenticated and current_user.can(Permission.MANAGE_USERS) %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            USERS <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('auth.register') }}">Register user</a></li>
                            <li><a href="{{ url_for('main.list_users') }}">List users</a></li>
                            <li><a href="{{ url_for('main.list_moderators') }}">List moderators</a></li>
                            <li><a href="{{ url_for('main.search_users') }}">Search users</a></li>
                            <li><a href="{{ url_for('main.list_expensenotes') }}">List expense notes</a></li>
                            <li><a href="{{ url_for('main.user_stats') }}">Statistics</a></li>
                        </ul>
                    </li>
                {%  endif %}

                {%  if current_user.is_authenticated and current_user.can(Permission.MANAGE_SKILLS) %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            SKILLS <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('main.list_skills') }}">List skills</a></li>
                            <li><a href="{{ url_for('main.add_skill') }}">Add skill</a></li>
                        </ul>
                    </li>
                {%  endif %}

                {%  if current_user.is_authenticated and current_user.can(Permission.MANAGE_RESOURCES) %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            RESOURCES <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('main.list_resources') }}">List resources</a></li>
                            <li><a href="{{ url_for('main.add_resource') }}">Add resource</a></li>
                        </ul>
                    </li>
                {%  endif %}

                {%  if current_user.is_authenticated and current_user.can(Permission.MANAGE_PAYMENTS) %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            PAYMENTS <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('main.anonymous_payment') }}">Make anonymous payment</a></li>
                            <li><a href="{{ url_for('main.list_payments') }}">List payments</a></li>
                            <li><a href="{{ url_for('main.export_payments') }}">Export payments</a></li>
                        </ul>
                    </li>
                {%  endif %}

                {%  if current_user.is_authenticated and current_user.can(Permission.CHANGE_SETTINGS) %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            SETTINGS <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('main.change_settings') }}">Change</a></li>
                        </ul>
                    </li>
                {%  endif %}

                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.photo_url(size=18) }}">
                        PROFILE <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                        <li><a href="{{ url_for('main.list_reservations', id=current_user.id) }}">Reservations</a></li>
                        <li><a href="{{ url_for('auth.change_password') }}">Change password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">LOG IN</a></li>
                <li><a href="{{ url_for('auth.register') }}">REGISTER</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ pagedown.include_pagedown() }}

<script type=text/javascript>
$(document).ready(function() {
    $('tr.clickable-row').click(function() {
        var href = $(this).find("a").attr("href");
        if(href) {
            window.location = href;
        }
    });
});

$('.pull-down').each(function() {
    $(this).css('margin-top', $(this).parent().height()-$(this).height())
});
</script>

{% endblock %}

app/webapp/templates/base_stripped.html
{% extends "bootstrap/base.html" %}

{% block title %}{{ config['APP_NAME'] }}{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/webapp/templates/calendar.html
{% extends "base_stripped.html" %}
{% import "resource/_calendar.html" as calendar %}

{% block title %}{{ config['APP_NAME'] }}{% endblock %}

{% block page_content %}
    <br>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 align="center">After <a href="{{ url_for('auth.register') }}">registration</a> and <a href="{{ url_for('auth.login') }}">login</a>,
                you can make <a href="{{ url_for('main.list_resources') }}">reservations</a> or
                <a href="{{ url_for('main.edit_profile') }}">manage your account</a>.</h3>
            </div>
        </div>

        {{ calendar.fullcalendar_content() }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ calendar.fullcalendar_scripts('available', none, none, '.available_getdata', '#378006') }}
{% endblock %}

app/webapp/templates/delete_confirmation.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ config['APP_NAME'] }} - Delete {{ name }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Delete {{ name }}</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/webapp/templates/index.html
{% extends "base.html" %}
{% import "resource/_calendar.html" as calendar %}

{% block title %}{{ config['APP_NAME'] }}{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>BUDA::lab Administrative Backend</h1>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>After <a href="{{ url_for('auth.register') }}">registration</a> and <a href="{{ url_for('auth.login') }}">login</a>,
                you can make <a href="{{ url_for('main.list_resources') }}">reservations</a> or
                <a href="{{ url_for('main.edit_profile') }}">manage your account</a>.</p>

                This is the availability calendar. It shows you when the lab is open and what volunteer will be present. You can click on a block for more info.<br>
                Always remember to make a reservation if you want to use a machine!
            </div>
        </div>

        {{ calendar.fullcalendar_content() }}
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}

    {% if current_user.can(Permission.MANAGE_RESOURCES) %}
        {{ calendar.fullcalendar_scripts('available', none, '.available_setdata', '.available_getdata', '#378006') }}
    {% else %}
        {{ calendar.fullcalendar_scripts('available', none, none, '.available_getdata', '#378006') }}
    {% endif %}
{% endblock %}